#!/usr/bin/env python3
"""Genera le schede ristorante individuali e gli indici griglia per paese."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# slug: (nome, zona, cucina, specialita, costo, location, stelle, tel, valut, orari, note,
#        chef, menu[], foto[(path, fonte)], extra)
MQ = {
 "rist-zanzibar": ("Zanzibar", "Le Marin", "\U0001F41F Pesce creolo contemporaneo",
   "Crabe cirique farci · marmite de la Mer", "\U0001F4B0\u20AC\u20AC\u20AC",
   "\U0001F3D6\ufe0f spiaggia elegante", "\u2605\u2605\u2605\u2605", "0596 74 08 46",
   "TA 4,2/5 (1368)", "mar\u2013sab 12\u201314:30 / 18:30\u201322 \u00b7 dom pranzo \u00b7 lun chiuso",
   "11 bd All\u00e8gre, Plage du Bourg \u00b7 restaurantzanzibar.com \u00b7 prenotare in alta stagione; menu \u201cH\u00e9ritage Carib\u00e9en\u201d",
   "Julie",
   ["Crabe cirique farci", "Gravlax de poisson local", "Foie gras mi-cuit au rhum vieux",
    "Tartare de poisson", "Marmite de la Mer", "Menu \u201cH\u00e9ritage Carib\u00e9en\u201d"],
   [("rist-zanzibar.jpg", "restaurantzanzibar.com (wixstatic)"), ("rist-zanzibar-2.jpg", "restaurantzanzibar.com (wixstatic)")],
   ""),
 "rist-kokoarum": ("KokOaRum Bar", "Marina du Marin", "\U0001F969 Grill e burger caraibico",
   "Burger garnis \u00b7 colombo de poisson", "\U0001F4B0\u20AC\u20AC",
   "\u2693 marina, musica live", "\u2605\u2605\u2605\u00bd", "0596 48 02 21",
   "Google 4,0/5 (747) \u00b7 TA 3,5/5 (281)", "serale \u00b7 happy hour 17\u201319 \u00b7 concerti mer e ven",
   "Sui pontili della marina \u00b7 gestione Fr\u00e9d\u00e9ric Chaneli\u00e8re e Val\u00e9rie dal 2017",
   "ND (gestori: F. Chaneli\u00e8re e Val\u00e9rie)",
   ["Burger garnis 15\u201320 \u20ac", "Colombo de poisson", "Cocktail signature 10\u201312 \u20ac"],
   [("rist-kokoarum.jpg", "bellemartinique.com")], ""),
 "rist-ti-cozy": ("Ti Cozy", "Sainte-Anne", "\U0001F370 Crêperie bretona",
   "Galette sarrasin \u00b7 glaces artigianali", "\U0001F4B0\u20AC",
   "\U0001FAB6 rustico curato", "\u2605\u2605\u2605\u2605\u2605", "0696 05 44 10 / 0596 97 74 89",
   "TA 5,0/5 (198), Travellers' Choice 2024", "11\u201321:30 \u00b7 chiusura settimanale divergente tra le fonti \u26a0\ufe0f chiamare",
   "8 av. J.-M. Tjibaou \u00b7 N\u00b01 TA a Sainte-Anne \u00b7 pochi coperti",
   "Fred (cucina) e Franck Respriget (sala), bretoni",
   ["Galette sarrasin da 6 \u20ac", "Crêpe Saint-Jacques", "Crêpes dolci", "Glaces artigianali locali", "Jus frais maison"],
   [("rist-ti-cozy.jpg", "TripAdvisor media CDN"), ("rist-ti-cozy-2.jpg", "TripAdvisor media CDN")],
   "email franck.respriget29@orange.fr"),
 "rist-boubou": ("Snack Boubou Bokits", "Sainte-Anne", "\U0001F959 Street food creolo",
   "Bokit morue/poulet", "\U0001F4B0\u20AC",
   "\U0001F959 snack da strada", "\u2605\u2605\u2605\u2605\u00bd", "0696 50 01 93 / 0596 76 28 46",
   "Google 4,7/5 (305) \u00b7 TA 4,7/5 (316), Travellers' Choice", "lun-gio-ven-sab-dom 10:30\u201315 \u00b7 chiusura settimanale divergente \u26a0\ufe0f",
   "32 rue Fran\u00e7ois Saffache, accanto alla chiesa (anche punto clearance!) \u00b7 attivo dal 2006 \u00b7 contante",
   "ND (\u201cBoubou\u201d)",
   ["Bokit morue ~8 \u20ac", "Bokit poulet ~8 \u20ac", "Bokit poisson/viande 8\u201310 \u20ac", "Fruit punch"],
   [],
   "\U0001F534 foto non ancora scaricabili (CDN protetti) \u2014 recuperare al controllo mensile"),
 "rist-le-m": ("Le M", "Sainte-Anne", "\U0001F41F Creativa fronte mare",
   "Pesce fresco del giorno", "\U0001F4B0\u20AC\u20AC\u20AC",
   "\U0001F37D\ufe0f elegante informale", "\u2605\u2605\u2605\u2605\u00bd", "0596 76 75 43",
   "TA 4,7/5 (372) \u00b7 Petit Futé 4,4/5 (127)", "lun chiuso \u00b7 mer\u2013sab 12\u201314:30 / 19\u201321:30 \u00b7 dom pranzo",
   "Rue du bord de mer \u00b7 le-mrestaurant.com \u00b7 stessi gestori del Paille Coco",
   "Kévin Julians",
   ["Cucina semi-gastronomica creativa", "Pesce fresco del giorno", "Menu sul sito"],
   [("rist-le-m.jpg", "le-mrestaurant.com"), ("rist-le-m-2.jpg", "le-mrestaurant.com")], ""),
 "rist-cour-creole": ("La Cour Créole", "Sainte-Anne", "\U0001F969 Creola tradizionale",
   "Colombo de poulet \u00b7 boudin antillais", "\U0001F4B0\u20AC\u20AC",
   "\U0001F334 patio creolo", "\u2605\u2605\u2605\u2605\u00bd", "0596 62 59 18 / 0696 28 44 39",
   "TA 4,5/5 (344)", "mar\u2013mer 10\u201318 \u00b7 gio\u2013sab 10\u201321 \u00b7 dom 10\u201318 \u00b7 lun chiuso",
   "15 rue J.-M. Tjibaou \u00b7 adatto alle famiglie",
   "ND",
   ["Colombo de poulet ~16 \u20ac", "Accras de morue ~8 \u20ac", "Boudin antillais", "Tarte goyave", "Flan coco"],
   [("rist-cour-creole.jpg", "bellemartinique.com")], ""),
 "rist-daurade": ("La Daurade", "Sainte-Anne", "\U0001F41F Creola popolare",
   "Accras \u00b7 colombo pesce del giorno", "\U0001F4B0\u20AC",
   "\U0001FAB6 semplice, locale", "\u2605\u2605\u2605\u2605", "0696 85 87 55 / 0696 27 61 64",
   "TA 4,0/5 (205)", "tutti i giorni, pranzo e sera",
   "3 rue du Capitaine Constant, vicino al mercato del pesce \u00b7 buon rapporto qualit\u00e0/prezzo",
   "ND",
   ["Accras", "Boudin antillais", "Poulet boucané", "Langoustes secondo arrivo", "Colombo pesce del giorno",
    "Menù entrée+plat+dessert 22 \u20ac"],
   [("rist-daurade.jpg", "sito jimdo del ristorante")], ""),
 "rist-delims": ("Delim's", "Sainte-Anne", "\U0001F41F Langouste e lambi",
   "Langouste \u00b7 lambi \u00b7 chatrou", "\U0001F4B0\u20AC\u20AC\u20AC",
   "\U0001F37D\ufe0f raffinato", "\u2605\u2605\u2605\u2605\u00bd", "0696 35 48 59 (prenotazioni 0696 75 49 13)",
   "TA 4,7/5 (140)", "lun-gio-ven-sab 19\u201322 \u00b7 sab-dom 12\u201315 \u00b7 chiuso mar\u2013mer",
   "Avenue Nelson Mandela \u00b7 ledelims.com \u00b7 anche traiteur \u00b7 pizze d'asporto la sera",
   "Marie-Claude (cucina), sorella Marie-Laure in sala",
   ["Langouste", "Lambi", "Chatrou", "Formule entrée+plat+cocktail o plat+dessert+cocktail 40 \u20ac"],
   [("rist-delims.jpg", "ledelims.com")], "email ledelims@gmail.com"),
 "rist-basilic-beach": ("Basilic Beach", "Pointe Marin", "\U0001F41F Beach creolo rivisitato",
   "Pesce fresco \u00b7 cocktail", "\U0001F4B0\u20AC\u20AC",
   "\U0001F3D6\ufe0f sulla spiaggia", "\u2605\u2605\u2605\u2605", "0696 32 67 92",
   "TA 4,1/5 (406) \u00b7 Petit Futé 4,5/5 (26)", "tutti i giorni",
   "Plage de Pointe Marin \u00b7 vista splendida, buon rapporto qualit\u00e0/prezzo",
   "ND",
   ["Pesce fresco del giorno", "Cucina creola rivisitata", "Cocktail"],
   [("rist-basilic-beach.jpg", "jimcdn (sito ristorante)")], ""),
 "rist-pirates-beach": ("Pirates Beach", "Anse Caritan", "\U0001F969 Burgers antillais",
   "Boeuf mijoté aux épices \u00b7 accras", "\U0001F4B0\u20AC\u20AC",
   "\U0001F3D6\ufe0f beach club con sdraio", "\u2605\u2605\u2605\u2605\u00bd", "0696 86 08 64 / 0596 67 07 56",
   "TA 4,5/5 (302)", "mer\u2013dom ~12\u201317/18 \u00b7 chiuso lun\u2013mar",
   "Plage de l'Anse Caritan \u26a0\ufe0f non Pointe Marin come spesso riportato \u00b7 restaurantpiratesbeach.com \u00b7 prenotazione solo via modulo online",
   "Cédric",
   ["Burgers antillais ~15 \u20ac", "Tapas", "Boeuf mijoté aux épices locales", "Accras du Rocher"],
   [("rist-pirates-beach.jpg", "bellemartinique.com")], ""),
 "rist-kreol-k-fe": ("Kreol K Fé", "Anse à l'Âne", "\U0001F969 Caraibica-francese",
   "Colombo \u00b7 accras \u00b7 hamburger", "\U0001F4B0\u20AC\u20AC",
   "\U0001FAB6 casuale, colazione/pranzo/cena", "\u2605\u2605\u2605\u2605", "0596 65 55 31 / 0696 94 44 65",
   "TA 4,1/5 (303)", "lun\u2013sab 6\u201324 \u00b7 dom 10\u201324",
   "Rue du Caret, Anse à l'Âne (Les Trois-Îlets) \u00b7 tappa comoda dall'ancoraggio",
   "ND",
   ["Colombo", "Accras", "Hamburger"],
   [("rist-kreol-k-fe.jpg", "bellemartinique.com")], "email kkf.martinique@gmail.com"),
 "rist-oasis": ("L'Oasis", "Anses d'Arlet", "\U0001F41F Pesce e tartare",
   "Thon mi-cuit \u00b7 tartare de poisson", "\U0001F4B0\u20AC\u20AC",
   "\U0001F305 terrazza sul mare", "\u2605\u2605\u2605\u2605", "0596 48 00 69",
   "Petit Futé \u2192 \u2605\u2605\u2605\u2605 (stima)", "mer\u2013dom \u00b7 chiusura annuale set\u2013ott",
   "19 bd des Arlésiens, bourg \u00b7 sul molo",
   "ND",
   ["Thon mi-cuit", "Tartare de poisson", "Daurade sauce wasabi", "Entrecôte", "Burger", "Vacherin coco"],
   [("rist-oasis.jpg", "bellemartinique.com")], ""),
 "rist-palmeiras": ("Palmeiras Karaïb", "Le Diamant", "\U0001F969 Brasiliana-caraibica",
   "Tartare pesce del giorno \u00b7 accras", "\U0001F4B0\u20AC\u20AC",
   "\U0001F305 vista Rocher, tramonto", "\u2605\u2605\u2605\u2605\u00bd", "0596 76 12 99",
   "Google 4,4/5 (880) \u00b7 TA 4,2/5 (1029)", "lun 12\u201323 \u00b7 mer\u2013sab 12\u201323 \u00b7 dom 12\u201315 \u00b7 chiuso martedì",
   "Spiaggia Dizac/Anse Caffard davanti al Rocher (ex New Cap) \u00b7 riaperto 31/07/2026 dopo sargassi",
   "ND",
   ["Tartare pesce del giorno", "Burger pane fatto in casa", "Camembert fritto", "Accras du Rocher", "Tapas", "Cocktail"],
   [("rist-palmeiras.jpg", "bellemartinique.com")], ""),
 "rist-havana-cafe": ("Havana Café", "Pointe du Bout", "\U0001F969 Fajitas e grill",
   "Fajitas \u00b7 crêpes \u00b7 cocktail maison", "\U0001F4B0\u20AC\u20AC",
   "\U0001F3B6 musica live, animato", "\u2605\u2605\u2605\u00bd", "0596 66 15 93",
   "Petit Futé 3,6/5", "7/7 servizio continuato 11:30\u201323 (mezzanotte nel week-end)",
   "Village Créole, rue du Chacha, Les Trois-Îlets \u00b7 havana-cafe-martinique.fr",
   "ND",
   ["Fajitas mexicaines", "Tartares di pesce fresco", "Grillades", "Salades composées",
    "Galettes e crêpes dolci", "Coupes glacées", "Cocktail maison (carta 20\u201330 \u20ac)"],
   [("rist-havana-cafe.jpg", "havana-cafe-martinique.fr (wixstatic)")],
   "email havanacafemartinique@gmail.com"),
 "rist-sous-le-vent": ("Sous le Vent", "Sainte-Luce", "\U0001F41F Bistronomico pesce",
   "Daurade snackée sauce aimé \u00b7 langouste flambée", "\U0001F4B0\u20AC\u20AC",
   "\U0001F305 bistrot sul mare", "\u2605\u2605\u2605\u2605\u2605", "0596 28 63 70 / 0607 76 45 92",
   "TA 4,7/5 (138), Travellers' Choice 2025 (n\u00b05/777 a Sainte-Luce)",
   "mer\u2013dom 12\u201314 / 18\u201321 \u00b7 chiuso lun\u2013mar",
   "15 bd Kennedy, fronte mare \u00b7 \U0001F534 CHIUSURA ANNUALE 27/04\u201315/10/2026",
   "Lionel (cucina) e Annie in sala, bretoni",
   ["Accras à notre façon 7 \u20ac", "Rillette de thazard créole 7 \u20ac", "Boudin créole grillé 7 \u20ac",
    "Linguine au chorizo 22 \u20ac", "Daurade snackée sauce aimé 25 \u20ac", "Tartare de thon aller-retour 26 \u20ac",
    "Tentacules de poulpe crème d'ail 27 \u20ac", "Langouste flambée 46 \u20ac"],
   [("rist-sous-le-vent.jpg", "sito Google Business del ristorante")],
   "email r.souslevent@gmail.com"),
 "rist-zandoli": ("Le Zandoli", "Fort d'Alet", "\U0001F37D\ufe0f Gastronomica fusion",
   "Menu Découverte 70 \u20ac \u00b7 completo 95 \u20ac", "\U0001F4B0\u20AC\u20AC\u20AC",
   "\U0001F3DB\ufe0f boutique hotel 5*, vista baia", "\u2605\u2605\u2605\u2605", "0596 59 88 00",
   "TA 4,2/5 (809)", "ven\u2013sab 19\u201322 (ultima comanda a tavola)",
   "La Suite Villa, route du Fort d'Alet, Les Trois-Îlets \u2014 domina la baia di FdF \u00b7 menu PDF aggiornato lug 2026 \u00b7 taxi dalla rada",
   "Julien Fournet",
   ["Découverte 70 \u20ac: mise en bouche, chatrou, l'\u0152uf, le Loup, l'Instant Planteur",
    "Completo 95 \u20ac: + canard, formaggio"],
   [("rist-zandoli.jpg", "la-suite-villa.com")], ""),
}

GUA = {
 "rist-toumbana": ("Le Toumbana", "Terre-de-Haut (Les Saintes)", "\U0001F41F Creola in giardino",
   "Langouste \u00b7 accras", "\U0001F4B0\u20AC\u20AC", "\U0001F334 giardino tropicale", "\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google positive", "**DATO MANCANTE**",
   "A piedi dal pontile \u00b7 pranzo consigliato \u00b7 prenotare la langouste \u00b7 menu 15\u201324 \u20ac",
   "ND", ["Langouste", "Accras", "Pesce del giorno"], [], ""),
 "rist-ketty": ("Chez Ketty", "Deshaies", "\U0001F41F Langouste grigliata",
   "Langouste (prenotarla al mattino)", "\U0001F4B0\u20AC\u20AC", "\U0001F334 case créole in giardino", "\u2605\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google 4,7/5 (217)", "**DATO MANCANTE**",
   "N2 entrée gîtes Migneret", "ND", ["Langouste grigliata"], [], ""),
 "rist-savane": ("La Savane", "Deshaies", "\U0001F41F Francese-caraibica",
   "Pesce fresco \u00b7 colombo", "\U0001F4B0\u20AC\u20AC", "\U0001F305 vista mare", "\u2605\u2605\u2605\u2605\u00bd",
   "**DATO MANCANTE**", "Google 4,5/5 (568)", "**DATO MANCANTE**",
   "Bd des Poissonniers \u00b7 a piedi dall'ancoraggio", "ND", ["Pesce fresco", "Colombo"], [], ""),
 "rist-madras": ("Le Madras", "Deshaies", "\U0001F41F Creola fronte mare",
   "Accras \u00b7 thon", "\U0001F4B0\u20AC\u20AC", "\U0001FAB6 bordo mare, set TV", "\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google 4,3/5 (398)", "**DATO MANCANTE**",
   "7 rue de la Vague Bleue \u00b7 location della serie \u201cMeurtres au paradis\u201d", "ND",
   ["Accras", "Thon", "Piatti creoli"], [], ""),
 "rist-raf": ("Chez Raf", "Deshaies", "\U0001F37D\ufe0f Raffinata caraibica",
   "Pesce creativo", "\U0001F4B0\u20AC\u20AC\u20AC", "\U0001F37D\ufe0f elegante informale, cocktails", "\u2605\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google 4,9/5 (~250)", "**DATO MANCANTE**",
   "Vista mare \u00b7 tra i migliori del bourg \u00b7 menu 35\u201355 \u20ac", "ND", ["Pesce creativo"], [], ""),
 "rist-anse-gourmande": ("L'Anse Gourmande", "Deshaies", "\U0001F41F Caraibica",
   "Pesce \u00b7 prodotti locali", "\U0001F4B0\u20AC\u20AC", "\U0001FAB6 locale nuovo", "\u2605\u2605\u2605\u2605\u2605*",
   "**DATO MANCANTE**", "Google 4,9/5 (35) \u2014 pochi dati", "**DATO MANCANTE**",
   "Apertura recente: valutazioni da monitorare", "ND", ["Pesce", "Prodotti locali"], [], ""),
 "rist-lucullus": ("Le Lucullus", "Sainte-Anne", "\U0001F41F Creola-francese",
   "Pesce \u00b7 langouste", "\U0001F4B0\u20AC\u20AC", "\U0001F305 terrazza", "\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google 4,3/5 (1366)", "**DATO MANCANTE**",
   "Fronte mare \u00b7 classico affidabile della spiaggia", "ND", ["Pesce", "Langouste"], [], ""),
 "rist-cabanon": ("Le Cabanon", "Sainte-Anne", "\U0001F37D\ufe0f Franco-caraibica creativa",
   "Menu creativo stagionale", "\U0001F4B0\u20AC\u20AC", "\U0001FAB6 piccolo, curato", "\u2605\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google 4,9/5 (148)", "**DATO MANCANTE**",
   "Prenotare, pochi coperti", "ND", ["Menu creativo stagionale"], [], ""),
 "rist-coquillage": ("Le Coquillage", "Sainte-Anne", "\U0001F41F Frutti di mare",
   "Crustacés \u00b7 pesce", "\U0001F4B0\u20AC\u20AC", "\U0001F3D6\ufe0f fronte spiaggia", "\u2605\u2605\u2605\u2605\u00bd",
   "**DATO MANCANTE**", "Google 4,5/5 (199)", "**DATO MANCANTE**",
   "Per gli amanti dei frutti di mare", "ND", ["Crustacés", "Pesce"], [], ""),
 "rist-balaou": ("Le Balaou", "Sainte-Anne", "\U0001F41F Tataki di tonno",
   "Tataki de thon \u00b7 pesce", "\U0001F4B0\u20AC\u20AC", "\U0001F305 terrazza rilassata", "\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google 4,3/5 (405)", "**DATO MANCANTE**",
   "Buona carta dei vini", "ND", ["Tataki de thon", "Pesce"], [], ""),
 "rist-zagaya": ("Le Zagaya", "Saint-François", "\U0001F41F Pieds dans l'eau",
   "Crabe farci \u00b7 dorade al riso nero", "\U0001F4B0\u20AC\u20AC", "\U0001F3D6\ufe0f spiaggia, tramonto", "\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google positive", "**DATO MANCANTE**",
   "Comodo dalla marina/laguna \u00b7 carta ampia 10\u201350 \u20ac", "ND",
   ["Crabe farci", "Dorade al riso nero"], [], ""),
 "rist-playa": ("La Playa", "Marie-Galante", "\U0001F41F Locale rivisitata",
   "Pesce \u00b7 boudin créole", "\U0001F4B0\u20AC\u20AC", "\U0001F3D6\ufe0f beach front", "\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google positive", "**DATO MANCANTE**",
   "Da abbinare al giro dell'isola in scooter \u00b7 da 25 \u20ac", "ND",
   ["Pesce", "Boudin créole"], [], ""),
 "rist-pere-labat": ("La Table du Père Labat", "Grand-Bourg", "\U0001F41F Antillana-francese",
   "Lambi \u00b7 dolci al rum", "\U0001F4B0\u20AC\u20AC", "\U0001FAB6 tradizionale", "\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google positive", "**DATO MANCANTE**",
   "Vicino alle distillerie Bielle/Poisson \u00b7 menu 15\u201330 \u20ac", "ND",
   ["Lambi", "Boudin", "Dolci al rum"], [], ""),
 "rist-planteur": ("Le Planteur", "Gosier", "\U0001F969 Poulet boucané",
   "Poulet boucané \u00b7 ouassous", "\U0001F4B0\u20AC\u20AC", "\U0001F334 corte creola", "\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google positive", "**DATO MANCANTE**",
   "Tappa comoda dall'Îlet du Gosier \u26a0\ufe0f verificare approdo \u00b7 da 20 \u20ac", "ND",
   ["Poulet boucané", "Lambi", "Ouassous"], [], ""),
 "rist-rayon-soleil": ("Le Rayon de Soleil", "Anse-Bertrand", "\U0001F37D\ufe0f Creativa locale",
   "Menù degustazione", "\U0001F4B0\u20AC\u20AC\u20AC", "\U0001F305 vista oceano atlantico", "\u2605\u2605\u2605\u2605",
   "**DATO MANCANTE**", "Google positive", "**DATO MANCANTE**",
   "Hôtel Toubana \u00b7 dopo la visita alla Pointe de la Grande Vigie \u00b7 menu 25\u201360 \u20ac",
   "ND", ["Menù degustazione"], [], ""),
}


# ═══ GRENDINE + VIRGIN (dati verificati: bequia.travel, bequiatourism, CCA 11/2025, Horizon 2025, yachtharbours) ═══
BEQ = {
 "rist-jacks": ("Jack's Beach Bar","Princess Margaret Beach","🐟 Caraibica beachfront",
   "Jack's Fried Chicken · PM Burger","💰€€","🏖️ direttamente sulla spiaggia","★★★★",
   "+1 784 458-3809","Google/TA positive · top10 isola","lun–gio 12–21 · ven–dom 9–21",
   "info@jacksbeachbar.com · jacksbeachbar.com · Tempura okra · tel/fax 457-3762 · cell 498-7562",
   "ND",["Jack's Fried Chicken","PM Burger","Tempura Okra","Pesce del giorno"],[],""),
 "rist-macs": ("Mac's Pizza & Kitchen","Belmont Walkway","🍕 Pizzeria",
   "Lobster pizza · conch fritters","💰€€","🌊 fronte baia, lucine","★★★★",
   "+1 784 458-3474 / 528-4213","Google 4,3/5 (685) · TA 4,3 (397)","dom–gio 11:30–21 · ven–sab 22 · chiuso mer",
   "Dal 1980 · lasagne homemade · lime pie · happy hour ven 17–18:30 · macspizzabequia.com · prenotare",
   "ND",["Lobster pizza (stagione)","Don't Be A Jerk (jerk chicken)","Conch fritters","Lasagne homemade","Lime pie"],[],""),
 "rist-frangipani": ("Frangipani Hotel Restaurant","Belmont Walkway","🍽️ Caraibica-internazionale",
   "Thursday Jump Up · conch chowder","💰€€–€€€","🌊 waterfront storico","★★★★",
   "+1 784 458-3255","Citato in '1000 Places to See Before You Die'","colazione 07:30–10:30 · pranzo 11–15 · cena 18:30–22 · chiuso set",
   "Fondato dal figlio di J. 'Son' Mitchell · BBQ con Elite steel band il giovedì · frangipanibequia.com",
   "ND",["Conch chowder","Baked chicken rice-coconut","Lobster","BBQ buffet (gio)"],[],"prenotazione cena consigliata, essenziale il giovedì"),
 "rist-figtree": ("The Fig Tree","Belmont Walkway","🍲 Bequiana autentica",
   "Cucina locale speziata","💰€€","🌳 giardino","★★★★",
   "+1 784 457-3008","Google positiva","nov–mar 8–22 · apr–ott 11–20 · chiuso mar",
   "Cheryl Johnson · musica alcune sere · programma su Bequia This Week",
   "Cheryl Johnson",["Piatti locali speziati"],[],""),
 "rist-whaleboner": ("Whaleboner Inn","Belmont","🦴 West Indian",
   "Lobster · fish & chips","💰€€€","🐋 bar in mandibola di balena","★★★★",
   "+1 784 458-3233","Google positiva","08–21 · bar fino tardi",
   "Jump-up lun/ven/sab · main EC$46–89",
   "Ruth Hinckson",["Lobster","Fish & chips","Steak"],[],""),
 "rist-marias": ("Maria's French Terrace","Front Street","🥐 Francese-caraibica",
   "Cucina francese · carta dei vini","💰€€€","🌅 vista Admiralty Bay","★★★★",
   "+1 784 458-3337 / 458-3422","Google positiva","07:30–10:30 · 12–15 · 19–tardi",
   "Di fronte al dinghy dock · prenotare per gruppi",
   "ND",["Cucina francese","Cocktail"],[],""),
 "rist-fernandos": ("Fernando's Hideaway","Collina sopra Lower Bay","🐟 Bequiana autentica",
   "Pesce pescato dal cuoco · goat water (sab)","💰€€€","🏡 intimo, pochi coperti","★★★★★",
   "+1 784 458-3758 · WA +1 784 430-0478","TA molto positive","solo domenica 19–22 · chiuso 1 lug–1° sab nov",
   "Ex cuoco di nave; 'Nando' pesca personalmente · prenotare",
   "Fernando ('Nando')",["Pesce del giorno","Goat water soup (sab)"],[],""),
 "rist-keegans": ("Gracie's Beachside (ex Keegan's)","Lower Bay","🐟 Locale di spiaggia",
   "BBQ del sabato · piatti locali","💰€€","🏖️ beachside","★★★★",
   "+1 784 458-3530 / 457-3472","Google positiva","giorno · BBQ sabato",
   "keegansbequia.org",
   "ND",["BBQ del sabato","Piatti locali"],[],"email keegansbequia@yahoo.com"),
 "rist-dawns": ("Dawn's Creole Restaurant","Lower Bay Beach","🍲 Creola",
   "Menu del giorno · frutti di mare","💰€","🏖️ fine spiaggia ovest","★★★★½",
   "ND","Google 4,6/5 (156)","giorno",
   "Beach bar semplice con cucina locale apprezzata",
   "Dawn",["Pesce fresco","Piatti creoli"],[],""),
 "rist-barone": ("Bar One","Port Elizabeth Harbour (galleggiante)","🍹 Bar & snack",
   "Rum punch","💰€€","⛵ unico bar galleggiante, alimentato a solare","★★★★",
   "water taxi EC$10 dal jetty","Google positiva","fino all'ultimo water taxi",
   "Ivor Simpson · si può nuotare dal pontone · @baronebequia",
   "Ivor Simpson",["Rum punch ~US$9","Cocktail"],[],""),
 "rist-sugarreef": ("Sugar Reef Café","Industry Bay","🍽️ Raffinata",
   "Piatti freschi · acqua di cocco e rum","💰€€","🌴 by the waterside, baia deserta","★★★★",
   "ND","Google positiva","giorno (stagione)",
   "Su Crescent Beach, lato atlantico: via mare solo con meteo calmo",
   "ND",["Piatti freschi","Acqua di cocco"],[],""),
}
MUS = {
 "rist-basils": ("Basil's Bar","Britannia Bay","🐟 Caraibica iconica",
   "Lobster · sunset","💰€€€","🌴 sul molo, leggendaria","★★★★",
   "via Mustique Company","Google positiva","lunch & dinner · Blues Festival ultima sett. gennaio",
   "Sul molo di Britannia Bay · jump-up il mercoledì · mustique-island.com",
   "ND",["Lobster","Rum punch"],[],""),
 "rist-cottonhouse": ("Cotton House","Estate","🍽️ Elegante",
   "Cucina resort","💰€€€€","🏛️ piantagione storica","★★★★",
   "su prenotazione","—","pranzo/cena su prenotazione",
   "Old plantation house · servizio hotel 5*",
   "ND",["Menu resort"],[],""),
}
MAY = {
 "rist-coconut": ("Coconut Restaurant & Bar","Salt Whistle Bay","🐟 Caraibica",
   "Pesce · langousta","💰€€","🏖️ sulla baia","★★★",
   "ND","Guida CCA 11/2025","giorno/sera (stagione)",
   "Sulla spiaggia di Salt Whistle",
   "ND",["Pesce","Langousta"],[],""),
 "rist-lastbar": ("The Last Bar Before the Jungle","Salt Whistle Bay","🍹 Bar & grill",
   "Grill · cocktail","💰€€","🌴 fine spiaggia","★★★",
   "ND","Horizon 2025 · CCA","giorno (stagione)",
   "Operativo post-Beryl; nuovo breakwater in baia",
   "ND",["Grill","Cocktail"],[],""),
 "rist-nadies": ("Nadie's Bar & Restaurant","Salt Whistle Bay","🐟 Locale",
   "Pesce fresco","💰€€","🏖️","★★",
   "ND","Guida CCA 11/2025","stagione","ND",
   "ND",["Pesce"],[],""),
 "rist-islandparadise": ("Island Paradise","Costa ovest","🐟 Locale",
   "Pesce","💰€€","🌊","★★",
   "ND","Guida CCA 11/2025","stagione","ND",
   "ND",["Pesce"],[],""),
 "rist-dview": ("D'View Sports Bar & Restaurant","Costa ovest","🍽️ Mista",
   "—","💰€€","⛰️ vista","★★",
   "ND","Guida CCA 11/2025","stagione","ND",
   "ND",["Menu del giorno"],[],""),
}
UNI = {
 "rist-anchorageyc": ("Anchorage Yacht Club","Clifton","🐟 Caraibica",
   "Pesce del giorno","💰€€","⚓ waterfront Clifton","★★★",
   "ND","Guida CCA/Compass","giorno",
   "Sul waterfront di Clifton, classico diportisti",
   "ND",["Pesce del giorno"],[],""),
 "rist-sunbeach": ("Sunbeach & Eat (Seckie & Vanessa)","Chatham Bay","🍖 Grill di spiaggia",
   "Pesce/grill","💰€€","🏖️ baia selvaggia ovest","★★★",
   "ND","Horizon update 2025","stagione",
   "In ricostruzione post-Beryl: frequentare per supportare",
   "Seckie & Vanessa",["Grill","Pesce"],[],""),
}
CAN = {
 "rist-soho": ("Soho House Canouan","Grand Bay area","🍽️ Internazionale",
   "Take-out per yacht","💰€€€","🌱 resort","★★★",
   "+784 530-7400","—","su richiesta",
   "Consegne grocery/lavanderia/take-out per yacht in rada · reception.canouan@sohohouse.com · Doyle",
   "ND",["Menu resort","Take-out yacht"],[],""),
 "rist-sandylane": ("Sandy Lane Yacht Club Restaurant","Charlestown","🍽️ Marina",
   "—","💰€€€","⚓ marina","★★★",
   "via slycr.com","Recensioni Horizon 2025","sera",
   "Presso la marina; fuel dock",
   "ND",["Menu marina"],[],""),
}
VIR = {
 "rist-foxys": ("Foxy's Bar","Great Harbour, Jost Van Dyke","🍹 Bar leggendario",
   "Grill · rum","💰€€","⚓ porto d'ingresso","★★★★",
   "ND","Icona BVI","giorno/sera",
   "Istituzione; il Capodanno a Foxy's è famoso",
   "Foxy Callwood",["Grill","Painkiller"],[],""),
 "rist-soggydollar": ("Soggy Dollar Bar","White Bay, Jost Van Dyke","🍹 Beach bar",
   "Painkiller (nato qui)","💰€€","🏖️ si approda a nuoto","★★★★",
   "ND","Icona","giorno",
   "Dollari bagnati alla barra · day anchorage",
   "ND",["Painkiller"],[],""),
 "rist-willyt": ("Willy T (William Thornton)","The Bight, Norman Island","🍹 Bar galleggiante",
   "—","💰€€","⛵ schooner galleggiante","★★★★",
   "ND","Icona","giorno/sera",
   "Mooring field di Norman; snorkel agli Indians/Caves",
   "ND",["Drink","Snack"],[],""),
 "rist-cooperisland": ("Cooper Island Beach Club","Manchioneel Bay, Cooper","🍽️ Eco-resort",
   "Craft rum distillery","💰€€€","🌱 sostenibile","★★★",
   "cooperislandbeachclub.com","—","sera",
   "Mooring field proprio · distilleria artigianale",
   "ND",["Craft rum","Piatti resort"],[],""),
 "rist-bitterend": ("Bitter End Yacht Club","North Sound, Virgin Gorda","🍽️ Resort nautico",
   "—","💰€€€","⚓ icona North Sound","★★★",
   "beyc.com","—","in stagione","Ricostruito post-uragani",
   "ND",["Menu resort"],[],""),
 "rist-indigo": ("Indigo Beach House","Cane Garden Bay, Tortola","🐟 Caraibica",
   "—","💰€€","🏖️ baia famosa","★★",
   "ND","Moorings blog","giorno",
   "Vicino alla distilleria Callwood",
   "ND",["Piatti caraibici"],[],""),
}
SVI = {
 "rist-wallilabou": ("Wallilabou Anchorage","Wallilabou Bay","🍽️ Turistica",
   "—","💰€€","🎬 set Pirates of the Caribbean","★★",
   "ND","—","giorno",
   "Il set del film è il ristorante; baia con boe",
   "ND",[],[],""),
 "rist-youngisland": ("Young Island Resort","Young Island","🍽️ Resort",
   "—","💰€€€€","🏝️ isola privata","★★",
   "ND","—","su prenotazione",
   "Traghetto privato da Calliaqua",
   "ND",[],[],""),
}


def scheda(paese, slug, d):
    nome, zona, cucina, spec, costo, loc, stelle, tel, valut, orari, note, chef, menu, foto, extra = d
    L = [f"# {nome}", "",
         f"[← Tutti i ristoranti](../10-ristoranti.md)", "",
         "| Campo | Dettaglio |", "|---|---|",
         f"| Zona | {zona} |",
         f"| Cucina | {cucina} |",
         f"| Specialità | {spec} |",
         f"| Costo | {costo.replace(chr(0x1F4B0)+' ', '')} per persona senza bevande |",
         f"| Location | {loc} |",
         f"| Mappa | [Google Maps](https://www.google.com/maps/search/?api=1&query={nome.replace(' ','+')}+{zona.replace(' ','+')}) |",
         f"| Contatti | {tel} |",
         f"| Valutazioni | {valut} → {stelle} |",
         f"| Orari | {orari} |"]
    L += ["", "## Menu", ""]
    L += [f"- {m}" for m in menu]
    L += ["", f"**Chef**: {chef}", "", "## Foto", ""]
    if foto:
        for fn, src in foto:
            L += [f"![{nome}]({{}})".format(f"img/{paese}/{fn}"), "", f"*Fonte: {src}*", ""]
    else:
        L += ["*Foto non ancora disponibili — recuperare al controllo mensile.*", ""]
    L += [f"**Note**: {note}"]
    if extra:
        L += ["", f"**Extra**: {extra}"]
    return "\n".join(L) + "\n"

def indice(paese, dati):
    righe = []
    for slug, d in dati.items():
        nome, zona, cucina, spec, costo, loc, stelle = d[0], d[1], d[2], d[3], d[4], d[5], d[6]
        costo_s = costo.replace("\U0001F4B0", "").strip()
        righe.append(f"| [{nome}](ristoranti/{slug}.md) | {zona} | **{costo_s}** | **{cucina}** | *{spec}* | **{loc}** | {stelle} |")
    return righe

for paese, dati in (("martinica", MQ), ("guadalupa", GUA), ("grenadine/bequia", BEQ),
                    ("grenadine/mustique", MUS), ("grenadine/mayreau", MAY),
                    ("grenadine/union-island", UNI), ("grenadine/canouan", CAN),
                    ("grenadine/st-vincent", SVI), ("grenadine/tobago-cays", {}),
                    ("virgin-islands", VIR)):
    outdir = ROOT / paese / "ristoranti"
    if not dati: continue
    outdir.mkdir(parents=True, exist_ok=True)
    for slug, d in dati.items():
        (outdir / f"{slug}.md").write_text(scheda(paese, slug, d), encoding="utf-8")
    righe = indice(paese, dati)
    p = ROOT / paese / "10-ristoranti.md"
    t = p.read_text(encoding="utf-8")
    start = t.index("## Griglia generale")
    end = t.index("## App e fonti")
    griglia = ("## Griglia generale\n\n"
               "| Ristorante | Zona | Costo | Cucina | Specialità | Location | Stelle |\n"
               "|---|---|---|---|---|---|---|\n" + "\n".join(righe) + "\n\n")
    p.write_text(t[:start] + griglia + t[end:], encoding="utf-8")
print("generate", len(MQ), "+", len(GUA), "schede")
